name: SPHEXA docs

on: [push, pull_request]

jobs:
  docvalidation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Doc Requirements
        run: |
          python -m pip install -r docs/requirements.txt
      - name: Check format of rst files
        run: |
          pwd
          ls -l
          doc8 docs/
      - name: Build documentation
        run: |
          make -C docs html
